### ISSUE TITLE
Update Request to 4.1.2

### ISSUE THREAD

**Issue by xscd** [flathub/org.electrum.electrum#27] opened 2021-04-13 19:39 UTC
Current version on Flathub is 4.0.4 it would be great to get a bump to version 4.1.2 

https://github.com/spesmilo/electrum/releases/tag/4.1.2

**Comment by A6GibKm** [comment] 2021-04-13 21:11
Current is [4.0.9](https://github.com/flathub/org.electrum.electrum/blob/master/org.electrum.electrum.json#L77) I just forgot to update the metainfo. Thanks, since they dont do tagged releases there is no way for me to notice this, will try to update it soon.

**Comment by xscd** [comment] 2021-04-14 00:14
Yeah since they don't do tagged releases its not possible to get notifications inside GitHub right? How do you manage to track those apps? https://github.com/spesmilo/electrum/releases.atom would RSS help?

**Comment by A6GibKm** [comment] 2021-04-17 14:03
@xscd Could you test #28?

**Comment by xscd** [comment] 2021-04-20 00:11
I tested #28 and noticed wayland is enabled by default and it causes crashes (upstream: https://github.com/spesmilo/electrum/issues/6542) where you wrote that it defaults to xorg (https://github.com/flathub/org.electrum.electrum/pull/17) but that wasn't the case. I had to disable wayland from flatseal to stop crashes. Other than that everything looks fine.

**Comment by A6GibKm** [comment] 2021-04-20 07:27
Yes, I added Wayland support back some time ago since I was not able to reproduce said crashes after a certain update to QT or electrum. If you still have crashes I will remove the flag again, thanks for the feedback.

**Comment by A6GibKm** [comment] 2021-04-25 14:46
@xscd I removed wayland support and will merge as soon as it build. Please test it and tell me if wayland was properly removed or if it needs further work.

**Comment by xscd** [comment] 2021-04-25 22:14
Tested now I can create a new wallet without a crash (the crash happened when creating a new wallet and typing a password) 
![Screenshot from 2021-04-26 01-11-33](https://user-images.githubusercontent.com/46658470/116011191-69e02080-a62c-11eb-9a0d-5587731b7522.png)

Everything is fine now. One more thing that is left is to update the version metadata to 4.1.2 in flathub. 

![Screenshot from 2021-04-26 01-12-57](https://user-images.githubusercontent.com/46658470/116011249-ab70cb80-a62c-11eb-8ae2-62a7e1d1f810.png)

**Comment by A6GibKm** [comment] 2021-04-26 21:17
Thanks, I always forget that. Should be fixed by #29

**Comment by xscd** [comment] 2021-04-27 09:39
Thanks,everything is okay now. Feel free to close the issue. For future updates would the RSS enough for you to track new updates or would you mind me opening issues on the repository?

**Comment by A6GibKm** [comment] 2021-04-27 14:21
The rss is fine, but sometimes I dont check it. Please feel free to open an issue if I dont update it in a timely fashion.

**Closed as completed by A6GibKm** 2021-04-27 14:21 UTC
